services:
  accounts:
    image: "olukol/account-microservice:v2"
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - olukotun
  loans:
    image: "olukol/loan-microservice:v3"
    container_name: loan-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - olukotun
  cards:
    image: "olukol/cards-microservice:v3"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - olukotun
networks:
  olukotun:
    driver: "bridge"